name: Build Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: ./.github/workflows/build-modules.yml
    with:
      base: ${{ github.event.pull_request.base.sha }}
      publish: false
    secrets: inherit
